// 성경 66권 메타데이터: [id, 한국어 이름, 영어 이름, 장 수]
// testament: id 1–39 구약, 40–66 신약
const BOOKS = [
  [1, "창세기", "Genesis", 50],
  [2, "출애굽기", "Exodus", 40],
  [3, "레위기", "Leviticus", 27],
  [4, "민수기", "Numbers", 36],
  [5, "신명기", "Deuteronomy", 34],
  [6, "여호수아", "Joshua", 24],
  [7, "사사기", "Judges", 21],
  [8, "룻기", "Ruth", 4],
  [9, "사무엘상", "1 Samuel", 31],
  [10, "사무엘하", "2 Samuel", 24],
  [11, "열왕기상", "1 Kings", 22],
  [12, "열왕기하", "2 Kings", 25],
  [13, "역대상", "1 Chronicles", 29],
  [14, "역대하", "2 Chronicles", 36],
  [15, "에스라", "Ezra", 10],
  [16, "느헤미야", "Nehemiah", 13],
  [17, "에스더", "Esther", 10],
  [18, "욥기", "Job", 42],
  [19, "시편", "Psalms", 150],
  [20, "잠언", "Proverbs", 31],
  [21, "전도서", "Ecclesiastes", 12],
  [22, "아가", "Song of Solomon", 8],
  [23, "이사야", "Isaiah", 66],
  [24, "예레미야", "Jeremiah", 52],
  [25, "예레미야애가", "Lamentations", 5],
  [26, "에스겔", "Ezekiel", 48],
  [27, "다니엘", "Daniel", 12],
  [28, "호세아", "Hosea", 14],
  [29, "요엘", "Joel", 3],
  [30, "아모스", "Amos", 9],
  [31, "오바댜", "Obadiah", 1],
  [32, "요나", "Jonah", 4],
  [33, "미가", "Micah", 7],
  [34, "나훔", "Nahum", 3],
  [35, "하박국", "Habakkuk", 3],
  [36, "스바냐", "Zephaniah", 3],
  [37, "학개", "Haggai", 2],
  [38, "스가랴", "Zechariah", 14],
  [39, "말라기", "Malachi", 4],
  [40, "마태복음", "Matthew", 28],
  [41, "마가복음", "Mark", 16],
  [42, "누가복음", "Luke", 24],
  [43, "요한복음", "John", 21],
  [44, "사도행전", "Acts", 28],
  [45, "로마서", "Romans", 16],
  [46, "고린도전서", "1 Corinthians", 16],
  [47, "고린도후서", "2 Corinthians", 13],
  [48, "갈라디아서", "Galatians", 6],
  [49, "에베소서", "Ephesians", 6],
  [50, "빌립보서", "Philippians", 4],
  [51, "골로새서", "Colossians", 4],
  [52, "데살로니가전서", "1 Thessalonians", 5],
  [53, "데살로니가후서", "2 Thessalonians", 3],
  [54, "디모데전서", "1 Timothy", 6],
  [55, "디모데후서", "2 Timothy", 4],
  [56, "디도서", "Titus", 3],
  [57, "빌레몬서", "Philemon", 1],
  [58, "히브리서", "Hebrews", 13],
  [59, "야고보서", "James", 5],
  [60, "베드로전서", "1 Peter", 5],
  [61, "베드로후서", "2 Peter", 3],
  [62, "요한일서", "1 John", 5],
  [63, "요한이서", "2 John", 1],
  [64, "요한삼서", "3 John", 1],
  [65, "유다서", "Jude", 1],
  [66, "요한계시록", "Revelation", 22],
];

// 책 번호(1–66) → USFM/Paratext 책 코드 (API.Bible 챕터 ID에 사용)
const USFM = [null,
  "GEN","EXO","LEV","NUM","DEU","JOS","JDG","RUT","1SA","2SA",
  "1KI","2KI","1CH","2CH","EZR","NEH","EST","JOB","PSA","PRO",
  "ECC","SNG","ISA","JER","LAM","EZK","DAN","HOS","JOL","AMO",
  "OBA","JON","MIC","NAM","HAB","ZEP","HAG","ZEC","MAL","MAT",
  "MRK","LUK","JHN","ACT","ROM","1CO","2CO","GAL","EPH","PHP",
  "COL","1TH","2TH","1TI","2TI","TIT","PHM","HEB","JAS","1PE",
  "2PE","1JN","2JN","3JN","JUD","REV",
];

const VERSIONS = {
  web: { label: "WEB", full: "World English Bible (현대 영어)" },
  kjv: { label: "KJV", full: "King James Version (1611)" },
  krv: { label: "개역한글", full: "개역한글판 (1961)" },
  ceb: { label: "CEB", full: "Common English Bible (온라인, YouVersion)" },
  niv: { label: "NIV", full: "New International Version 2011 (온라인, YouVersion)" },
  nirv: { label: "NIrV", full: "New International Reader's Version 2014 — 쉬운 영어 (온라인, YouVersion)" },
  nasb: { label: "NASB", full: "New American Standard Bible 2020 (온라인, YouVersion)" },
  amp: { label: "AMP", full: "Amplified Bible (온라인, YouVersion)" },
  bsb: { label: "BSB", full: "Berean Standard Bible (온라인, YouVersion)" },
  grctr: { label: "그리스어 원문", full: "Scrivener's Textus Receptus 1894 — 그리스어 신약 원문 (온라인, YouVersion)" },
  esv: { label: "ESV", full: "English Standard Version (온라인, YouVersion)" },
  nlt: { label: "NLT", full: "New Living Translation (온라인, YouVersion)" },
};

// YouVersion Platform에서 실시간으로 불러오는 번역본과 버전 ID
// unavailable: 앱 키에 아직 라이선스가 없는 번역본 — 선택 불가로 표시.
//   라이선스가 승인되면 이 플래그만 지우면 된다.
// ntOnly: 신약(마태복음 이후)만 제공하는 판본.
// lang: 카탈로그 검색 시 사용할 언어 코드 (기본 en).
const ONLINE_VERSIONS = {
  niv: { id: 111, pattern: /new international version/i },
  nirv: { id: 110, pattern: /international reader/i },
  nasb: { id: 2692, pattern: /new american standard/i },
  amp: { id: 1588, pattern: /amplified bible/i },
  bsb: { id: 3034, pattern: /berean standard/i },
  grctr: { id: 183, pattern: /textus receptus 1894/i, lang: "grc", ntOnly: true },
  ceb: { id: 37, pattern: /common english bible/i, unavailable: true },
  esv: { id: 59, pattern: /english standard version/i, unavailable: true },
  nlt: { id: 116, pattern: /new living translation/i, unavailable: true },
};
